// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CS_ParticleDelete

#include "./CSRandomFuncs.cginc"

#include "./CSParticlesStructure.cginc"

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<ParticuleShader> _Particules;

float time;

[numthreads(32, 1, 1)]
void CS_ParticleDelete(uint3 id : SV_DispatchThreadID)
{
    if (random(float2(time, id.x)) > 0.5)
    {
        _Particules[id.x]._lifespan = -1.0;
        _Particules[id.x]._spriteColor.a = 0.0;

    }
}
